# Generated by Django 3.1.4 on 2020-12-02 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='author',
            name='dead',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quote.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pubHouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quote.pubhouse'),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='page',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
