# Generated by Django 3.1.4 on 2020-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0002_auto_20201202_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='dead',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
