# Generated by Django 3.1.4 on 2020-12-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0004_quote_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year',
            new_name='pubYear',
        ),
        migrations.AddField(
            model_name='book',
            name='endYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='startYear',
            field=models.IntegerField(default=0),
        ),
    ]
