# Generated by Django 3.1.4 on 2020-12-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0005_auto_20201205_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quote.book'),
        ),
        migrations.AddField(
            model_name='quote',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
