# Generated by Django 3.1.4 on 2021-01-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0006_auto_20201221_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='endYear',
        ),
        migrations.RemoveField(
            model_name='book',
            name='startYear',
        ),
        migrations.AddField(
            model_name='quote',
            name='month',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='monthDay',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
