# Generated by Django 3.1.4 on 2021-01-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0007_auto_20210102_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='month',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='monthDay',
        ),
    ]
