# Generated by Django 3.1.4 on 2021-02-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0008_auto_20210102_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='dead',
        ),
        migrations.AddField(
            model_name='author',
            name='death',
            field=models.IntegerField(default=0, verbose_name='Death Year:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth',
            field=models.IntegerField(default=0, verbose_name='Birth Year:'),
        ),
    ]
