# Generated by Django 3.1.4 on 2021-02-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0009_auto_20210213_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='check',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Surname:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quote.author', verbose_name='Author:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='City:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubHouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quote.pubhouse', verbose_name='publishing House:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubYear',
            field=models.IntegerField(default=0, verbose_name='Publishing Year:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title:'),
        ),
        migrations.AlterField(
            model_name='pubhouse',
            name='houseName',
            field=models.CharField(max_length=100, verbose_name='Publishing House:'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quote.author', verbose_name='Author:'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quote.book', verbose_name='Book:'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of the Quote:'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='page',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Page:'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(verbose_name='Quote Text:'),
        ),
    ]
