# Generated by Django 3.1.4 on 2021-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0010_auto_20210215_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname', 'name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='pubhouse',
            options={'ordering': ['houseName']},
        ),
        migrations.AlterField(
            model_name='pubhouse',
            name='houseName',
            field=models.CharField(max_length=100, unique=True, verbose_name='Publishing House:'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='check',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>.', null=True, verbose_name='Date of the Quote:'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('surname', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
