# Generated by Django 3.1.4 on 2021-04-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0011_auto_20210228_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['date']},
        ),
    ]
